# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('condominium_association_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField()),
            ],
        ),
    ]
